version: "3.9"
services:
  postgres:
    container_name: postgres_auth
    image: postgres
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: password
    networks:
      - backend
    volumes:
      - ./db-data:/var/lib/postgresql/data/
      - ./sql:/docker-entrypoint-initdb.d/:ro
    ports:
      - 5434:5432

  pgadmin:
    container_name: pgadmin_auth
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pguser@postgres.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5050:80
    networks:
      - backend

  keycloak:
    container_name: keycloak_auth
    image: quay.io/keycloak/keycloak:19.0.3
    depends_on:
      - "postgres"
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres_auth/postgres
      KC_DB_PORT: 5434
      KC_DB_USERNAME: pguser
      KC_DB_PASSWORD: password
    ports:
      - 8081:8081
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
